### ISSUE TITLE
Error if only error code is returned

### ISSUE THREAD

**Issue by uded** [prabint/api-bank#6]
If I hit on one of our endpoints that might return a code other than 200, but with no body/message, I am getting NPE:

```
urlConnection.errorStream must not be null
java.lang.NullPointerException: urlConnection.errorStream must not be null
	at api.bank.repository.DefaultCoreRepository$executeRequest$2.invokeSuspend(DefaultCoreRepository.kt:37)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

According to HTTP standards, there is no obligation to return any message, simple status code is sufficient. In specific scenarios, this is a good solution.

**Comment by prabint** [comment]
Hi, thanks for reporting. I have applied a fix in https://github.com/prabint/api-bank/pull/7/commits/ac035ed8824d25e475ec6df89921fcae6f73364c and the new version `1.0.1` should be available once verified by JetBrain.
